---
- hosts: localhost
  connection: local

  collections:
    - amazon.aws

  vars:
    vpc_name: valarrr
    vpc_cidr: 10.10.1.0/24

  tasks:

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        state: present
        tags:
          deploymentID: "{{ deploymentID }}"
      register: vpc

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ region }}"
        tags:
          Name: "{{ vpc_name }}"
          deploymentID: "{{ deploymentID }}"
      register: subnet

    - name: Create ENI
      amazon.aws.ec2_eni:
        private_ip_address: "{{ private_ip }}"
        subnet_id: "{{ subnet.subnet.id }}"
        region: "{{ region }}"
        state: present
      register: eni

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          deploymentID: "{{ deploymentID }}"
      register: igw

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        instance_type: t2.micro
        image_id: "{{ image_id }}"
        state: present
        region: "{{ region }}"
        key_name: "{{ key }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        network:
          assign_public_ip: yes
          interfaces:
            - id: "{{ eni.interface.id }}"
        wait: yes
        wait_timeout: 500
        tags:
          deploymentID: "{{ deploymentID }}"
      register: vm

    - debug:
        var: vm

    - name: Allocate and associate Elastic IP
      amazon.aws.ec2_eip:
        region: "{{ region }}"
        device_id: "{{ vm.instances[0].instance_id }}"
        state: present
        tags:
          deploymentID: "{{ deploymentID }}"
