---
- name: Create S3 Bucket
  hosts: localhost
  connection: local
  collections:
    - amazon.aws

  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: my-test-aap-bucket-212121
        state: present
        region: us-west-1
