---
- name: Simple Azure VM create
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - azure.azcollection

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: test-rg
        location: eastus

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: test-rg
        name: testvm01
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        admin_password: Password@12345
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: "18.04-LTS"
          version: latest
        os_type: Linux
